### PR TITLE
Fix height 404

### PR DESCRIPTION
**Pull request by EmmanuelDrouin**
- Fix issue #171

### CODE REVIEW

**Comment by antho1404** [comment]
Screen Shot 2019-12-18 at 17 11 30

That's a new style to mix content and footer, I like it but I think it would be better not to have that ;)

**Comment by EmmanuelDrouin** [comment]
Haha, the problem comes from the height=100vh, i added an overflow hidden to fix this issue

**Comment by antho1404** [comment]
so now we cannot see anything...

Screen Shot 2019-12-18 at 17 56 18

**Comment by EmmanuelDrouin** [comment]
@antho1404 fixed, replace height by min-height in the scss to fix the problem

**Pull request merged**
