### PR TITLE
Update link CTA menu get started

### PR DESCRIPTION
**Pull request by EmmanuelDrouin**
- Replace internal link of the "get started" CTA in the menu by an external link to the get started page of the docs

To do:
- [x] Fix issue with the "menu" component 
@antho1404  External links are not working if they are at the first level of the menu. They are working if they are at the second level of the menu (submenu)

### CODE REVIEW

**Comment by antho1404** [comment]
@EmmanuelDrouin fix done, now the button can accept external links as well

**Comment by EmmanuelDrouin** [comment]
@antho1404 the issue is still here. The button in the menu is still not working with external links.
I've double check, every components are up to date. But the issue remain.

**Comment by antho1404** [comment]
It's working for me https://deploy-preview-241--mesg.netlify.app/
Make sure to refresh your cache maybe (cmd+shift+r)

**Comment by EmmanuelDrouin** [comment]
@antho1404 i can see on the deploy-preview it's working. For me it's not working locally (on my localhost), even with the cache refreshed. I don't know why. But anyway looks good on the preview, so let's merge this PR and move on.

**Comment by antho1404** [comment]
For information, it's probably because of your previous install

```
rm -rf node_modules
npm i
```

This should fix your issue

**Pull request merged**
