### PR TITLE
Get started page

### PR DESCRIPTION
**Pull request by EmmanuelDrouin**
The new Hub for developers, with all the resources to start learning MESG.

### CODE REVIEW

**Comment by antho1404** [comment]
Deploy preview for *mesg* ready!

Built with commit d08dd24e920b1c900a108ec6c9cdb89977d88c65

https://deploy-preview-192--mesg.netlify.com

**Comment by antho1404** [comment]
Could you split your work on the `ListSN` and the `CTA`, this is not related to this PR and should be done in 2 different PRs.

**Comment by antho1404** [comment]
A few feedback that I'm not sure are issues or stuff still WIP.

- [ ] The links on the card should be clickable (the full line)
- [ ] Commands are not valid eg: `mesg - cli process: create` instead of `mesg-cli process:create` (no space around the `-` and the `:`
- [ ] Title to change, @williamzmorgan any suggestion? 
- [ ] Icons of _help center_ and _see all_ looks weird on the left, should be on the right of the text
- [ ] Separator line in the card is not the full height (especially visible on the services)
- [ ] Link in the menu

**Comment by EmmanuelDrouin** [comment]
To do:

- [ ] Switch update on the List social network to another PR
- [ ] Switch update on the CTA card (add icon) to another PR
- [ ] Change from Table to List for the resources links
- [ ] Update design of the right icons on the resources links
- [ ] Finalize the Design of the illustration

**Comment by EmmanuelDrouin** [comment]
@antho1404 ready for review

**Pull request merged**
