### PR TITLE
Update Website

### PR DESCRIPTION
**Pull request by EmmanuelDrouin**
It started to be too complicated to manage all the PR and have a global overview on the project.

Also to avoid having multiple issues regarding too many PRs impacting each other i decided to merge everything into this PR.

Todo:
- [x] Update the content regarding MESG Token (ERC20) by just Token (native one) (@williamzmorgan)
- [x] Remove all monetary aspect in the content (@williamzmorgan)
- [x] Update Token page (@EmmanuelDrouin)
  - [x] Remove all marketing content
  - [x] Remove none technical docs
  - [x] Add CTA to the "token utility" article
  - [x] Remove monetary aspect (ATD, exchanges)
- [x] Token page - Replace Lorem ipsum CTA CARD bottom (@williamzmorgan)
- [x] Add an introduction section for Liteflow, bellow the entry points on the homepage (@EmmanuelDrouin)
- [x] Replace lorem ipsum of the Liteflow introduction section on the home page (@williamzmorgan)
- [x] Nav (menu+footer) (@EmmanuelDrouin)
  - [x] Remove Liteflow
  - [x] Switch "products" back to "Technology" 
  - [x] Add token into the "Technology" sub-menu
- [x] Clean up the store to remove useless content (@EmmanuelDrouin)
- [x] Delete Get started, Roadmap page (@EmmanuelDrouin)
- [x] Replace icons with a monetary aspect (@EmmanuelDrouin)
- [x] Remove mention of the Marketplace in the content (@antho1404)

### CODE REVIEW

**Comment by antho1404** [comment]
To clarify what needs to be done:
- Remove all reference to the "MESG Token" 
- Remove all monetary aspect of the token (ATD, exchanges)
- Introduce Liteflow, not as a product of MESG but more as a partner
- Focus on the Economy rather than Token (the token is here to supports the economy but don't need to be explained)

Note: It can be good if we can find something different than "economy" as it has a high connotation with money even if the [definition](https://en.wikipedia.org/wiki/Economy) is right

**Comment by EmmanuelDrouin** [comment]
I've added a list of tasks to do.

Also i would like to clarify that all financial, monetary, economic aspect should be remove from the content.

Your comment @antho1404 was open to confusion and misunderstanding on the subject.

MESG is about the technology, the economy is on Liteflow.

Instead of talking about economy we can focus on the "Fuel" of the ecosystem.

**Comment by EmmanuelDrouin** [comment]
@antho1404 i don't know why but i have the same issue all the time with external link at the first level of the menu...It's really annoying to have this issue and not being able to know why.

It's working fine on the preview.

**Comment by antho1404** [comment]
When it's working on the preview it's usually related to you local environment so you can clean it with
```
rm -rf node_modules
npm i
```
This should fix it

**Comment by EmmanuelDrouin** [comment]
**SDK Page** 

Mention of the "Marketplace"

> **Save development hours** 
The tools in the SDK make it easy to reuse any services, whether they are custom-built or shared from the community in the **Marketplace**.


**Services page**  

Mention of the "Marketplace" and the "MESG Token"

> **Earn while you sleep** 
All services listed on the **Marketplace** will earn **MESG Tokens** each time they are used within any other users' applications.

> **A decentralized network of services**
Our **marketplace** of app components and executions is a key part of our vision to create a decentralized network of services.

> **Automatic compatibility**
The open-source tools in the MESG SDK ensure that all services from the **Marketplace** are automatically compatible with each other.

> **Decentralized executions**
All services and apps in the **Marketplace** will soon be decentralized.

> Build your own **marketplace**
Add a decentralized **marketplace** to any existing solution. The SDK enables interoperability between all systems and features, so it’s a perfect solution to build and manage your own **marketplace** within your product.

> **Autonomous workflows**
Services from the **Marketplace** can be easily combined into powerful workflows and apps. React to Ethereum transactions being processed. Deploy and manage sidechains. The possibilities are endless.

> **Open economy**
The **Marketplace** is completely open, decentralized and self-regulating, so no single entity has control over participants or submissions, including MESG itself. The more services are used, the more tokens are earned.

**Token page**

Mention of the "MESG Token"

> **Secure the network**
All participants stake **MESG Tokens** to commit to availability and good behavior. Then, participants are rewarded for validating executions.

> **Buy and sell services**
Access to app components, called services, are bought and sold using **MESG Tokens**. Services can be used within any app, no complex coding required.

**MESG Foundation page**

Mention of the "Marketplace"

> **About the Foundation**
The SDK and **Marketplace** are developed by a global team of passionate developers for The MESG Foundation, a non-profit organization.

**FAQ page**

Mention of the "Marketplace", the "MESG Token" and Financial value

> **What is MESG?**
MESG is an application/workflow development platform made of a decentralized network of intercompatible services. Any API, blockchain or decentralized network can be connected to services.
Interoperability between all services are managed by the MESG Engine regardless of languages or data formats. Users sell or purchase intercompatible services in the open **MESG Marketplace**, allowing developers to save significant time and/or generate income from their work.

> **How much does MESG cost?**
Anyone can use MESG for free to build applications on a local computer. **However, not all functionalities will always be free.**
If developers want to use MESG’s decentralized network to run and execute their applications, they must first **pay MESG Tokens** to other network participants to run and secure their applications. **The MESG Foundation will not take a cut from transactions between users**
Developers and participants can also earn tokens by using MESG depending on their desired level of involvement. Developers who build services or help execute, validate events and tasks in applications will earn **MESG Tokens** for their participation.

> **How can I earn tokens with MESG?**
A self-regulating economy is a major part of MESG. Firstly, each time a new service is built, it can be shared and reused. The creators of services are free to choose **the price in MESG Tokens** that participants **will pay** to use the service. As part of this, service builders also decide how much each participant (emitters, validators and executors) **is paid** for their help.
Secondly, participants who commit to running their computers to support data processing in the Network **are paid** for their participation. The number of tokens each of these participants earns is determined by the Service’s creator, so participants can choose which processes will **be most lucrative** for them.

> **Do I need to be a developer to use MESG?**
With MESG’s currently-available functionalities, yes. Development skills are required to build services, and to combine services into applications.
**However, soon workflows will debut, allowing anyone to write a simple config file (no more than 20 lines of text), listing the desired services, events and tasks to be executed.**
As long as the desired services have been previously built and are available on **the Marketplace,** the MESG SDK software will read the config file and assemble the entire application on your behalf. This will allow anyone to build the back end of applications, with no coding skills required.

Workflow = Orchestrator, already available

@antho1404 can you review the content and remove the remaining mentions of the Marketplace, MESG Token, and financial values?

**Comment by antho1404** [comment]
Did some update on the content.
A few feedback here:

- @EmmanuelDrouin I think should we rename and redirect the `/mesg-marketplace` to `/mesg-registry`

- page marketplace > What's this "Build your own marketplace" what are we trying to say here? @williamzmorgan 

- The content was really outdated in some places
  - talking about workflow and not process
  - a lot of "coming soon" when we talked about the processes or decentralized network
This is really bad and this content should have been updated over time. Basically in some places, the website was communicating that the development was still at a state of a year ago if not more... I said it a few time and I will repeat it again but the content and website need to be in sync with the product and that your responsibilities to do keep this up to date.

**Comment by antho1404** [comment]
Another feedback, I find the call to action in the header confusing. We land on MESG but tell you to build on liteflow without knowing what it is.

What do you think about simply removing the call to actions in the header and just keep the one at the end of the page?

**Comment by EmmanuelDrouin** [comment]
@antho1404 the updates look good to me.

> * @EmmanuelDrouin I think should we rename and redirect the `/mesg-marketplace` to `/mesg-registry`

I was thinking to rename and redirect it to `/mesg-services` to be consistent with our communication. The entry  point on the home page is about "services", same for the links on the different part of the Website. But if you think `/mesg-registry` is better i'm ok with it.

Also i would like to rename and redirect `/mesg-orchestrator` to `/mesg-process` as we don't use the name orchestrator in the communication anymore, and for the same reason then above to be consistent.

> Another feedback, I find the call to action in the header confusing. We land on MESG but tell you to build on liteflow without knowing what it is.

Agree that it's kind of confusing.

> What do you think about simply removing the call to actions in the header and just keep the one at the end of the page?

The CTA that convert the most is the one in the header, there is not so many interaction with the one at the bottom (mostly because there is some random/useless section above it most of the time like newsletter, community, etc.)

Also you have to keep in mind that most of the users won't scroll to the bottom of the page So keeping the one in the header is actually very important.

I think even if it's a bit confusing in the website actual state, it could also intrigue the users and make them click on it. 

I will recommend to keep it for now, and find a way later to improve the clarity of it, instead of removing it and risking to not drive any traffic from MESG to Liteflow.

**Comment by williamzmorgan** [comment]
I agree that it feels weird to have that CTA at the top for Liteflow. It is sort of confusing because Liteflow has not been introduced yet. I would prefer it to be simply "Start building" and it links to MESG docs for advanced developers (why is this not linked somewhere, btw?). Or removing it as Anthony suggested. However, if it must be to Liteflow, we should perhaps change the CTA to "Build easier with Liteflow" "Build faster with Liteflow" or "Build on MESG easier with Liteflow". 

I also have changed the Token page title to "Economy" because this is mostly what the page is about, and saying Token may be confusing because of the prevalence of cryptocurrencies (in addition to our former ERC20). I think the rest of the content works with it, even with the changed title. If you guys are OK with this, we will need to change the URL as well (not sure how to do that).

**Comment by williamzmorgan** [comment]
The "Build your own Marketplace" was a use case we were promoting because of the ability to create ERC20 or ERC721 marketplaces within other technologies (e.g. BeachHead). I have removed this use case as it is now confusing and added a more relevant one.

**Comment by EmmanuelDrouin** [comment]
@williamzmorgan we don't link anything anymore at the moment to docs.mesg.com as this documentation is outdated regarding Liteflow ;)

The long term goal will be to have some links on mesg.com that will drive users who wants to know more to auto-generate advanced docs about the Engine on Github. The engine include MESG cli, services, processes. This advanced docs will be for very advance developers (cause super complicated), and just to give more information/context around the Engine. No conversion goal, no get started, etc.

It will be implemented later, cause the new docs are not ready at the moment. Coming soon ;)

**So to be clear: no more links to docs.mesg.com in our MESG communication for now**

Regarding your feedback about the CTA to Liteflow in the header, i agree with you on this:

> It is sort of confusing because Liteflow has not been introduced yet. And it kind of disrespects MESG as a standalone product.

I'm ok to remove the CTA in the header, as it's actually looks too much.

Good idea to rename the token page by economy. Anthony will take care of changing the URl.

**Comment by EmmanuelDrouin** [comment]
@antho1404 ready, you can work on the update of the URL for the SDK, services, process and token page

**Comment by antho1404** [comment]
done

**Comment by EmmanuelDrouin** [comment]
@antho1404 good for me, let's go?

**Pull request merged**
