### PR TITLE
Footer height on big screen

### PR DESCRIPTION
**Pull request by EmmanuelDrouin**
- Fix issue #177

### CODE REVIEW

**Comment by EmmanuelDrouin** [comment]
@antho1404 do you think we should set the flatline when the screen is bigger then 2000px width? Actually the Huge-breakpoint variable is set to 1700px width in the theme

**Comment by antho1404** [comment]
I don't mind much 1700px is fine for me or we can change the variable to 2000px. I let you make the call ;)

**Comment by EmmanuelDrouin** [comment]
I think we can keep it as 1700px for now. Otherwise we will need to adjust the angle of the background to match 2000px width.

**Comment by EmmanuelDrouin** [comment]
@antho1404 ready for review

**Pull request merged**
