### PR TITLE
add ATD price log page

### PR DESCRIPTION
**Pull request by ilgooz**

### CODE REVIEW

**Comment by antho1404** [comment]
@ilgooz I created a PR https://github.com/mesg-foundation/mesg.com/pull/95 with some fixes that I see for that but otherwise it's good for me

**Comment by NicolasMahe** [comment]
The lines of the table should contain both ETH and BTC amount

**Comment by antho1404** [comment]
Agree this is a secondary page, it should not be in the menu. I see:
- Footer > ATO Statistics
- Token page > ATO > Check the statistics

**Comment by antho1404** [comment]
close in favor of https://github.com/mesg-foundation/atd

**Pull request closed without merging**
