### PR TITLE
added sass support for styling

### PR DESCRIPTION
**Pull request by ilgooz**

### CODE REVIEW

**Comment by antho1404** [comment]
we already have css variables (defined here https://github.com/mesg-foundation/mesg.com/blob/master/layouts/default.vue) that is usually more than enough if we don't want to go really complex with the @include, @extend and stuff like that from sass.
What's the real reason for a sass support

**Comment by ilgooz** [comment]
> we already have css variables (defined here https://github.com/mesg-foundation/mesg.com/blob/master/layouts/default.vue) that is usually more than enough if we don't want to go really complex with the @include, @extend and stuff like that from sass.
> What's the real reason for a sass support

I mainly want to use nested style definitions for grouping styles instead of putting everything in a flat line. It really feels more readable and easy to manage to me. But It's not a must to have.
Other features are also nice to have, we can benefit from them as needed.

**Comment by antho1404** [comment]
nesting is nice feature.
@EmmanuelDrouin are you comfortable to work with sass ? do you know it ?
Basically nesting is:
```
.classx {
  .foo { ... }
  .bar { ... }
}
```
instead of
```
.classx .foo { ... } 
.classx .bar { ... }
```

Just want to make sure it's not adding too much complexity for @EmmanuelDrouin if it's just to have this in 1 or 2 places in the code.
Also in many cases this can be solved with components that embeds their own style with the `scoped` property and this simplifies a lot the css

**Comment by ilgooz** [comment]
I can coordinate with Manu as needed. :wink:

**Comment by EmmanuelDrouin** [comment]
@antho1404 i never used Sass before so i technically don't know anything about it.

If it's just like your example, a way to group the different css styles together i'm open to use it.

**Comment by ilgooz** [comment]
@antho1404 let's merge!

**Pull request merged**
